name: make_and_publish_all_pkgs
run-name: Package ${{ github.event.repository.name }}(${{ github.ref_name }}) for all platforms, Publish to ${{ inputs.deployment-environment }}
on:
  workflow_dispatch:
    inputs:
      deployment-environment:
        type: choice
        options:
          - development
          - testing
          - production
      commit-versioning:
        type: choice
        options:
          - default
          - yes
          - no
jobs:
  make-all-packages:
    strategy:
      matrix:
        development-environment: [ inputs.development-environment ]
        commit-versioning: [ inputs.commit-versioning ]
        include:
          - arch: amd64
            os: buster
    uses: ./.github/workflows/make_and_publish_pkgs.yml
