name: make_and_publish_all_pkgs
run-name: Package ${{ github.event.repository.name }}(${{ github.ref_name }}) for all platforms, Publish to ${{ inputs.deployment-environment }}
on:
  workflow_dispatch:
    inputs:
      deployment-environment:
        type: choice
        options:
          - development
          - testing
          - production
      commit-versioning:
        type: choice
        options:
          - default
          - yes
          - no
jobs:
  make-all-packages:
    strategy:
      matrix:
        include:
          - arch: amd64
            os: buster
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/make_and_publish_pkgs.yml
        with:
          arch: ${{ arch }}
          os: ${{ os }}
          development-environment: ${{ development-environment }}
          commit-versioning: ${{ commit-versioning }}
